spring.application.name=javabackend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/DietEaseProd
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true



# ==========================================
# HYBRID AI CONFIGURATION (Gemini Chat + Local Math)
# ==========================================

# 1. Routing the Universal Connector directly to Google Gemini
spring.ai.openai.api-key=AIzaSyCLgaGI31o4YVLS4QaeeAexMQvvf9U1oqE
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.chat.options.model=gemini-2.5-flash

# 2. Disable OpenAI's math engine so it uses your local transformers!
spring.ai.openai.embedding.enabled=false

# 3. Hibernate Safety
spring.jpa.hibernate.ddl-auto=update